---
- name: Install MySQL and TomCAT
  hosts: all
  become: yes

  roles:
    - { role: mysql, when: ansible_hostname == "ip-10-0-20-20" }
    - { role: tomcat, when: ansible_hostname == "ip-10-0-10-20" }
  